version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:234543744000:task-definition/aws-hello-world-rest-api:1"
        LoadBalancerInfo:
          ContainerName: "aws-hello-world-rest-api"
          ContainerPort: "80"
        PlatformVersion: "LATEST"